"""Recompute every number quoted in the report and the canvas.

    python analysis/report_stats.py            print the tables
    python analysis/report_stats.py --write    also write docs/report_stats.md

Nothing here is typed by hand: if the register changes, rerun this and the report follows.
"""
import argparse
from pathlib import Path

import geopandas as gpd
import pandas as pd

SOURCE = Path("data/processed/parking_rules.parquet")
OUT = Path("docs/report_stats.md")


def table(df, title):
    return f"### {title}\n\n{df.to_markdown(index=False)}\n"


def rule_types(areas):
    counts = areas["rule_type"].value_counts()
    df = pd.DataFrame({
        "Rule type": counts.index,
        "Areas": counts.values,
        "Share": (counts.values / len(areas) * 100).round(1),
    })
    return table(df, "Areas by rule type")


def reserved_for(areas):
    """What 'reserved' means in practice. Falls back to the Finnish field if labels are absent."""
    column = "space_type_en" if "space_type_en" in areas.columns else "tyyppi"
    counts = areas.loc[areas["rule_type"] == "reserved", column].value_counts(dropna=False)
    df = pd.DataFrame({"Reserved for": counts.index.fillna("not stated"), "Areas": counts.values})
    return table(df, "Reserved areas by space type")


def coverage(areas):
    counts = areas["status"].value_counts()
    meaning = {
        "official": "Complete rule published",
        "missing_hours": "Rule type known, hours missing",
        "uncertain": "Uncertain, with a stated reason",
    }
    df = pd.DataFrame({
        "Status": [meaning.get(s, s) for s in counts.index],
        "Areas": counts.values,
    })
    return table(df, "What the app can answer")


def neighbour_accuracy(known):
    """Hide each area's hours and copy them from its nearest area of the same class."""
    paired = pd.concat(
        gpd.sjoin_nearest(g[["geometry", "hours"]], g[["geometry", "hours"]],
                          exclusive=True, distance_col="dist")
        for _, g in known.groupby("luokka") if len(g) > 1
    )
    paired["match"] = paired["hours_left"] == paired["hours_right"]

    baseline = known["hours"].value_counts().iloc[0] / len(known) * 100
    headline = (
        f"Copying the nearest same-class area is correct "
        f"**{paired['match'].mean() * 100:.1f}%** of the time "
        f"({len(paired)} comparisons; ties add a few rows). Always guessing the most common "
        f"pattern scores **{baseline:.1f}%**.\n"
    )

    bins = pd.cut(paired["dist"], [0, 10, 50, 200, float("inf")],
                  labels=["0-10 m", "10-50 m", "50-200 m", "over 200 m"])
    by_dist = paired.groupby(bins, observed=True)["match"].agg(["mean", "size"]).reset_index()
    by_dist.columns = ["Distance to nearest same-class area", "Correct", "Areas"]
    by_dist["Correct"] = (by_dist["Correct"] * 100).round(1)
    return headline + "\n" + table(by_dist, "Accuracy by distance")


def prediction_gap(areas, known):
    """How far the areas we must predict sit from the areas we can learn from."""
    gap = pd.concat(
        gpd.sjoin_nearest(m[["geometry"]], known[known["luokka"] == k][["geometry"]],
                          distance_col="dist")
        for k, m in areas[areas["status"] == "missing_hours"].groupby("luokka")
        if (known["luokka"] == k).any()
    )
    d = gap["dist"]
    df = pd.DataFrame({
        "Measure": ["Areas measured", "Median distance", "Within 10 m", "Within 50 m",
                    "Within 200 m"],
        "Value": [f"{len(d)}", f"{d.median():.0f} m", f"{(d <= 10).mean() * 100:.1f}%",
                  f"{(d <= 50).mean() * 100:.1f}%", f"{(d <= 200).mean() * 100:.1f}%"],
    })
    return table(df, "Distance from a missing-hours area to the nearest area we can learn from")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--write", action="store_true", help=f"also write {OUT}")
    args = ap.parse_args()

    if not SOURCE.exists():
        raise SystemExit(f"{SOURCE} not found. Run: python pipeline/process.py")
    areas = gpd.read_parquet(SOURCE)
    known = areas[areas["hours"].notna()]

    parts = [
        f"# Report figures\n\nGenerated by `analysis/report_stats.py` from "
        f"`{SOURCE}`: {len(areas)} parking areas, {len(known)} of them with stated hours.\n",
        rule_types(areas),
        reserved_for(areas),
        coverage(areas),
        neighbour_accuracy(known),
        prediction_gap(areas, known),
    ]
    text = "\n".join(parts)
    print(text)
    if args.write:
        OUT.write_text(text)
        print(f"written to {OUT}")


if __name__ == "__main__":
    main()
